### ISSUE TITLE
[Task] Review licensing

### ISSUE THREAD

**Issue by alicerunsonfedora** [ProjectAliceDev/aliceos#2]
Currently, AliceOS is licensed under the Lesser GPL. However, given that we've overhauled Prospect Park, I think we could review our options and see if we want to switch licenses.

- [x] Find new license
- [ ] Make changes in Setup.aoscservice
- [ ] Add to root of directory
- [ ] Update AliceOS website (and Project Alice, if needed)

**Comment by sr229** [comment]
Possible licenses are MIT or BSD so non-free applications can use our repository. Eclipse Public License may work as well

**Comment by alicerunsonfedora** [comment]
After doing some preliminary research, I think we can work with either MIT or BSD.

- As nice as the EPL may be, we'll run into similar issues again with non-free uses of AliceOS (eg. Doki Doki Forces, Unscripted, etc.).
- The MIT works just fine as it's a KISS example of open-source licensing.
- Given that we use the 2-clause BSD license (or if necessary, FreeBSD), that's also a valid option with me.

**Comment by sr229** [comment]
We'll do a preliminary voting on Discord, whatever the crowd chooses, we'll go from that.

**Comment by alicerunsonfedora** [comment]
It also appears that our websites don't mention the license we're using on AliceOS, so an update to them might not be necessary.
