### ISSUE TITLE
Define standard for error message generation

### ISSUE THREAD

**Issue by alicerunsonfedora** [ProjectAliceDev/aliceos#32]
Typically, the RSODs and AliceOS errors in generally follow the same method of naming errors as Microsoft does with BSODs. However, it can get difficult trying to name it in this fashion. We should define a way to write errors that are human readable/understandable and are unique to AliceOS.

**Comment by alicerunsonfedora** [comment]
This might be an interesting way of handling errors. What if we did something similar to Java's exceptions? For instance:

- SetupInputNullException
- CallNullLabelException
- MissingCyanideInstrumentException
- InaccessibleBootDeviceException

In this fashion, the error is human-readable and isn't as jarring as the BSOD way of doing it.

**Comment by MysticQuack** [comment]
I think the original ones are currently fine, we just have to write them in a more understandable way:

- SETUP_FAULT_INPUT_UNRESPONSIVE
- ACT_FAULT_CALL_SUDDEN or ACT_FAULT_CALL_MISSING
- CYANIDE_FAULT_INSTRUMENT_MISSING
- BOOT_FAULT_DEVICE_INACCESSIBLE

Rough outline and it looks odd, but it works, and it does make sense.

**Comment by alicerunsonfedora** [comment]
That is without a doubt true. However, given AliceOS's playful and positive nature, the all capitals approach seems like shouting (not the greatest netiquette...).

**Comment by MysticQuack** [comment]
That looks fitting for the shouting error.

**Comment by alicerunsonfedora** [comment]
Alright, for comparisons:

## Regular-style
![aliceos new rsod 1](https://user-images.githubusercontent.com/13445064/46234778-d0521480-c345-11e8-88f0-f088137fd429.png)

## Java-style
![aliceos new rsod 2](https://user-images.githubusercontent.com/13445064/46234775-caf4ca00-c345-11e8-8652-7b2f7d8a18ef.png)

**Comment by MysticQuack** [comment]
Regular looks a lot better, really. And the font looks off for the 2nd one.

**Comment by alicerunsonfedora** [comment]
Also, thoughts on new RSOD sketch?

**Comment by cpgyuri** [comment]
Looks hot. Noelia is an awesome artist.

**Comment by alicerunsonfedora** [comment]
Just a development: we now offer an Error DB: https://errordb.aliceos.app

**Comment by sr229** [comment]
@alicerunsonfedora ~~Is it that time for me to write specs~~

Okay so this is my kind of Error Messages

## FS

- `FileSystemException_` / `ERR_FILESYSTEM_` Prefixes denoted. 
- Examples may be:
   - `NoPerm`/ `INSUFFICIENT_PERMISSIONS` if AOS has no FS permissions on a critical filesystem sector.
   - `UnreadableSector` / `SECTOR_INVALID` Sector is unreadable or invalid. (Used for critical directories).
   -  `CriticalFileMissing` / `CRITICAL_FILE_MISSING`  if a Critical Runtime file is missing.

## Screen
- `ScreenException_` / `ERR_SCREEN_` Prefixes denoted.
- Examples may be:
   - `UnterminatedProgress` / `PROGRESS_VOID` if Screen flow is missing a ending Screen to jump once reaching the final screen's scene in the screen index.
   - `MissingScreen` / `SCREEN_UNDEFINED` if a Screen is defined but does not exist within the VN context.
   - `ScreenCorrupt` / `SCREEN_INVALID` if a Screen is not a valid defined Screen.

## SIP/Security
- `SecurityAdditionsException_` / `ERR_SECADD_` Prefixes denoted.
- Examples may be:
     - `SIPComponentFailure` /`SIP_FAILED_INIT` if the SIP Component fails to init on runtime.
     -  `SIPCriticalFileCheckFail`/ `SIP_CRITICAL_FILE_INVALID` if SIP detects its files are different from its first indexed official files during the first init.
     - `SIPComponentProfileFail` / `SIP_COMPONENT_FAILED` if a SIP component failed early during the SIP call.

**Comment by alicerunsonfedora** [comment]
Best course of action would be to follow suit with @sr229 's system, but remove `ERR` for redundancy reasons. They do appear to be human readable and understandable. We should get these implemented as soon as possible and listed in the Error DB.

**Comment by alicerunsonfedora** [comment]
@MysticQuack I hereby assign you to make these additions to the Error DB as soon as possible.
